### ISSUE TITLE
Failed to copy image when obsidian window is deactivated.

### ISSUE THREAD

**Issue by chhs2131** [felipe-ds-lima/obsidian-copy-image-plugin#1]
Hello!
Thank you for making the useful plugin 🥳

<br/>

I have a problem when I copy the image from a deactivated obsidian window.

<img width="1662" alt="image" src="https://github.com/felipe-ds-lima/obsidian-copy-image-plugin/assets/10378777/7b6581cf-87c5-4ed4-988e-6ba2600d7433">

<br/>
<br/>

In this case,
1. Right click the image to be copied in obsidian.
2. Plugin Notice: Copied image URL to clipboard.
3. Paste it into some application.
4. (The application window is activated)
5. Right click the image to be copied in obsidian.
6. Plugin Notice: Failed to copy image URL to clipboard!

**Comment by felipe-ds-lima** [comment]
Hello!
I'll check the error and get back to you soon.

**Comment by felipe-ds-lima** [comment]
Are you using MAC or Linux?
In Windows, the window is automatically activated when you right-click.

**Comment by chhs2131** [comment]
I'm using a MAC :)

---[[ Spec ]]---
Model: MacBook Pro 16 M2
ChipSet: Apple M2 Pro
Memory: 16GB
OS Version: Sonoma 14.0

Obsidian Version: v1.5.3
Copy Image Plugin: v1.0.4

**Comment by felipe-ds-lima** [comment]
Apparently MacOs security blocks access to the clipboard when the application is not in focus, so I tried forcing focus on the window. It worked on Windows, but I don't have a Mac to test it. Can you please see if the change fixes the problem for you?

**Comment by chhs2131** [comment]
It works! but there are some issues left. 

The first click will fail to copy and 'obsidian window' will be activated. 
It seems that you want to do the copy action before the screen activation.

The next click will copy normally. Because theobsidian window is enabled.


<img width="1034" alt="image" src="https://github.com/felipe-ds-lima/obsidian-copy-image-plugin/assets/10378777/5504d6a3-63fc-4e89-b8e6-adfee9ae960a">

**Comment by felipe-ds-lima** [comment]
I released a new version that is now waiting for focus to copy, can you test it please?

**Comment by chhs2131** [comment]
That's cool, and it works!

![image](https://github.com/felipe-ds-lima/obsidian-copy-image-plugin/assets/10378777/506ab75d-3d9c-4f8d-a21a-845797f0389a)

**Comment by felipe-ds-lima** [comment]
Cool! Thank you very much for contributing to the plugin, I will close the issue.

If you encounter any other problem, please open a new issue.
