### ISSUE TITLE
I hope to support copying of GIFs

### ISSUE THREAD

**Issue by DanShui-Yu** [felipe-ds-lima/obsidian-copy-image-plugin#2]
Thank you for developing such a convenient tool.

**Comment by felipe-ds-lima** [comment]
Hi Dan, I'll try to support GIF. Thank you for helping to improve the plugin, I will bring updates soon.

**Comment by felipe-ds-lima** [comment]
Hello, sorry for the delay.
It is now possible to copy GIFs in version 1.0.9 of Copy Image, but the GIF is converted to PNG in the process. Unfortunately, Obsidian's clipboard doesn't allow copying formats other than PNG.

For now, I am closing the issue. Thank you very much for your contribution.
