### ISSUE TITLE
JPG "Failed to Copy..."

### ISSUE THREAD

**Issue by HazelcatDotNet** [felipe-ds-lima/obsidian-copy-image-plugin#3]
PNGs can reliably be copied, but JPGs cannot. Every time, it gives the "failed to copy" error. Is this a known issue, or am I doing something wrong?
Windows 10, Obsidian 1.5.12

**Comment by felipe-ds-lima** [comment]
Hello, thank you for contributing to the plugin, I will investigate what happened.

**Comment by cr941131** [comment]
> Hello, thank you for contributing to the plugin, I will investigate what happened.

I have the same issue and hope it gets resolved soon.

`obsidian_img/Clip_2024-09-08_13-56-16.jpg`

![Clip_2024-09-08_13-59-43](https://github.com/user-attachments/assets/6460c87e-69f2-4161-a2b2-454767abfed2)

**Comment by felipe-ds-lima** [comment]
Sorry, I've been very busy lately. I will work on a fix as soon as possible.

**Comment by felipe-ds-lima** [comment]
Good news! I’ve just fixed the issue in version 1.0.9 of Copy Image for the JPG format. However, it’s still not possible to copy formats other than: bmp, gif, jpeg, png, and tiff.

For now, I am closing the issue. Thank you very much for your contribution.
