### ISSUE TITLE
Feature request: Create a command palette action

### ISSUE THREAD

**Issue by laurensdc** [felipe-ds-lima/obsidian-copy-image-plugin#4]
Hi there,
Thank you so much for your contributions, this plugin rules!

It would be wonderful if there was a command palette action to copy image to clipboard.

For example, if my image looks like this:
`![[Pasted image 20240920160059.png|340]]`

Whenever any of the link is highlighted and I open command palette and execute "Copy image to clipboard", it would do the same action.

Keep on keeping on.

**Comment by felipe-ds-lima** [comment]
Thank you very much for the suggestion; I will work on that!

**Comment by felipe-ds-lima** [comment]
Good news! The feature has been added in version 1.1.0. You can either select the line where the image is located or select the image itself, then open the command palette and search for "Copy image to clipboard" to copy the selected image.

For now, I am closing the issue. Thank you very much for your contribution.

**Comment by laurensdc** [comment]
Works like an absolute charm. Thank you so much!

**Comment by miyl** [comment]
Great suggestion, and glad to see it's implemented now!

As far as I understand this is valid image syntax in markdown (and thus Obsidian):
```
![](https://wallpapercave.com/wp/rlTrbyc.jpg)
```
...as can fx. be seen here:
https://www.markdownguide.org/basic-syntax/#images-1

Could that syntax be supported as well?

**Comment by felipe-ds-lima** [comment]
Yes of course, I will add support for this syntax soon.

**Comment by miyl** [comment]
Thanks! Happy holidays and upcoming new year, by the way!
